# -*- coding: utf-8 -*-.

EMAIL_FROM = "info@rosti.cz"
EMAIL_HOST = "localhost"

DEFAULT_MYSQL_COMMAND = 'mysql -uroot'

CRISPY_TEMPLATE_PACK = 'bootstrap'

CONFIG = (
    ("pcp_invoices_item_desc", "Kredit hostingové služby Roští.cz", ""),
    ("default_web_machine", "localhost", ""),
    ("uwsgi_pidfile", "/var/run/uwsgi/app_%d.pid", ""),
    ("bind_conf", "/etc/bind/named.pandora.auto", ""),
    ("bind_master_zones_dir", "/etc/bind/zones", ""),
    ("bank_name", "FIO Banka", ""),
    ("email_server", "127.0.0.1", ""),
    ("default_mysql_machine", "localhost", ""),
    ("tax", 0, ""),
    ("dns_default_nss", "ns1.rosti.cz ns2.rosti.cz", ""),
    ("credit_wsgi", 1.0, ""),
    ("handle_dns", False, ""),
    ("credit_fee", 3.0, ""),
    ("credit_threshold", -7, ""),
    ("mysql_server", "localhost", ""),
    ("terms_url", "", ""),
    ("email_gid", 117, ""),
    ("default_mail_machine", "localhost", ""),
    ("uwsgi_conf", "/etc/uwsgi/config.xml", ""),
    ("nginx_conf", "/etc/nginx/sites-enabled/99_auto.conf", ""),
    ("dns_default_a", "87.236.194.121", ""),
    ("dns_minimum", 30, ""),
    ("apache_conf", "/etc/apache2/vhosts.d/99_auto.conf", ""),
    ("dns_retry", 1800, ""),
    ("nginx_listen", "[::]:80", ""),
    ("mysql_bind", "localhost", ""),
    ("nginx_ssl_listen", "[::]:443", ""),
    ("credit_static", 0.25, ""),
    ("pcp_invoices_api_url", "http://faktury.initd.cz/invoice/api/new_invoice/", ""),
    ("apache_user", "www-data", ""),
    ("pcp_invoices_api_key", "", ""),
    ("dns_slave", "", ""),
    ("apache_url", "127.0.0.1:8080", ""),
    ("apache_log_dir", "/var/log/webs/", ""),
    ("pcp_invoices_item_unit", "ks", ""),
    ("bank_account", "2200331030/2010", ""),
    ("dns_default_record_ttl", 3600, ""),
    ("ipv6", True, ""),
    ("dns_master", "", ""),
    ("handle_dns_secondary", False, ""),
    ("email", "info@rosti.cz", ""),
    ("var_symbol_prefix", 10, ""),
    ("bind_zone_conf", "/etc/bind/pri_auto/%s.zone", ""),
    ("credit_description", "1 kr. = 2 Kč", ""),
    ("maildir", "/var/mail", ""),
    ("nginx_init_script", "/etc/init.d/nginx", ""),
    ("credit_quotient", 0.5, ""),
    ("dns_default_nss_ips", "87.236.194.121 89.111.104.70", ""),
    ("fastcgi_wrapper_dir", "/var/www/%s/php5-wrap", ""),
    ("credit_wsgi_proc", 0.2, ""),
    ("pagination", 50, ""),
    ("dns_default_aaaa", "2a01:5f0:1022:1::1", ""),
    ("bind_init_script", "/etc/init.d/bind9", ""),
    ("bind_master_config_file", "/etc/bind/config.master.conf", ""),
    ("credit_currency", "CZK", ""),
    ("pgsql_server", "localhost", ""),
    ("dns_ns1", "ns1.example.com", ""),
    ("dns_ns2", "ns2.example.com", ""),
    ("dns_expire", 604800, ""),
    ("find_directory_deep", 2, ""),
    ("dns_refresh", 3600, ""),
    ("bind_slave_zones_dir", "/etc/bind/zones", ""),
    ("email_uid", 117, ""),
    ("dns_default_mx", "mail.rosti.cz.", ""),
    ("dns_email", "info.example.com", ""),
    ("nginx_log_dir", "/var/log/webx/", ""),
    ("credit_php", 1.0, ""),
    ("bind_slave_config_file", "/etc/bind/config.slave.conf", ""),
    ("auto_disable", True, ""),
    ("apache_init_script", "/etc/init.d/apache2", ""),
    ("mode", "nginx", ""),
    ("dns_mx", "mail.example.com", ""),
    ("uwsgi_memory", 192, ""),
    ("default_pgsql_machine", "localhost", ""),
)